import uuid from 'uuid'

import { TYPES_OF_SPECIALIZATIONS } from '../common'
import firstImg from '../assets/img/first.jpg'
import secondImg from '../assets/img/second.jpg'
import thirdImg from '../assets/img/third.jpg'
import fourthImg from '../assets/img/fourth.jpg'
import fifthImg from '../assets/img/fifth.jpg'
import sixthImg from '../assets/img/6th.jpg'

const announcements = [
  {
    uid: uuid(),
    img: firstImg,
    title: 'Питання і відповіді про контрактну форму навчання в ХНУРЕ',
    description: 'Зарахування до лав студентів вищого навчального закладу - завжди хвилюючий процес, під час якого навіть самі впевнені.',
    value: 'questions',
    url: '/',
  }, {
    uid: uuid(),
    img: secondImg,
    title: 'Розклад вступних іспитів в ХНУРЕ 2017',
    description: 'Розклад вступних іспитів ХНУРЕ і додаткових вступних випробувань для вступу',
    value: 'exams',
    url: '/',
  }, {
    uid: uuid(),
    img: thirdImg,
    title: 'Правила i порядок подачі документів в ХНУРЕ',
    description: 'Реєстрація електронних кабінетів вступників та завантаження додатків до документів.',
    value: 'documents',
    url: '/',
  }, {
    uid: uuid(),
    img: fourthImg,
    title: 'Правила прийому до ХНУРЕ у 2017 році',
    description: 'А ти знаєш, що: 1. Якщо ти іногородній, то маєш право на отримання місця в гуртожитку на період вступної кампанії. 2. Якщо у тебе повну середню загальну освіту, ти можеш: подати до 9 заяв на 4 спеціальності в своєму електронному кабінеті або особисто в Консультаційному центрі Приймальної комісії ХНУРЕ з 12 до 26 липня 2017 р вказавши пріоритети свого вибору',
    value: 'admissionRules',
    url: '/',
  }, {
    uid: uuid(),
    img: fifthImg,
    title: 'Спеціальності і спеціалізації для надходження на 1 курс в ХНУРЕ',
    description: '',
    value: 'specialities',
    url: '/',
  }, {
    uid: uuid(),
    img: sixthImg,
    title: 'Перелік пільг при вступі до ВНЗ, пільги ХНУРЕ і бланки для пільг',
    description: '',
    value: 'privileges',
    url: '/',
  },
];
const news = [
  {
    uid: uuid(),
    date: new Date(2018, 0, 12).getTime(),
    title: 'День відкритих дверей',
    description: 'ХНУРЕ запрошує на День відкритих дверей, який відбудеться 4 березня 2018 року. Початок - о 9-00. Харків, станція метро "Наукова", проспект Науки, 14.',
    url: null,
  }, {
    uid: uuid(),
    date: new Date(2018, 0, 13).getTime(),
    title: 'Олімпіада',
    description: 'Олімпіада ХНУРЕ буде проводитись з 1 березня.',
    url: null,
  }, {
    uid: uuid(),
    date: new Date(2018, 0, 19).getTime(),
    title: 'Правила отримання стипендії в ХНУРЕ',
    description: 'Що найприємніше в студентському житті? Можна було б сказати, що скільки людей - стільки і відповідей. ' +
    'Для кого-то - придбання знань, навичок, досвіду і професійного мислення...',
    url: 'http://nure.ua/wp-content/uploads/188-%D0%B2%D1%96%D0%B4-21.03.2017-' +
    '%D0%9F%D0%BE%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F_%D0%B7%D0%BC%D1%96%D0%BD' +
    '%D0%B8_1045_%D0%9D%D0%B0%D0%BA%D0%B0%D0%B7_%D0%92%D0%A0.pdf',
  },
];
const faculties = [
  {
    name: 'АКТ',
    uid: uuid(),
  }, {
    name: 'ЕЛБІ',
    uid: uuid(),
  }, {
    name: 'КН',
    uid: uuid(),
  }, {
    name: 'КІУ',
    uid: uuid(),
  }, {
    name: 'ІК',
    uid: uuid(),
  }, {
    name: 'ІРТЗІ',
    uid: uuid(),
  }, {
    name: 'ІТМ',
    uid: uuid(),
  },
];
const specialities = [
  {
    name: 'Інформаційні системи та технології',
    faculty_uid: faculties.find(elem => elem.name === 'КН').uid,
    uid: uuid(),
  }, {
    name: 'Інформаційні системи та технології',
    faculty_uid: faculties.find(elem => elem.name === 'ІРТЗІ').uid,
    uid: uuid(),
  }, {
    name: 'Інженерія програмного забезпечення',
    faculty_uid: faculties.find(elem => elem.name === 'КН').uid,
    uid: uuid(),
  }, {
    name: 'Телекомунікації та радіотехніка',
    faculty_uid: faculties.find(elem => elem.name === 'ІРТЗІ').uid,
    uid: uuid(),
  }, {
    name: 'Телекомунікації та радіотехніка',
    faculty_uid: faculties.find(elem => elem.name === 'ІК').uid,
    uid: uuid(),
  }, {
    name: 'Телекомунікації та радіотехніка',
    faculty_uid: faculties.find(elem => elem.name === 'АКТ').uid,
    uid: uuid(),
  }, {
    name: 'Системний аналіз',
    faculty_uid: faculties.find(elem => elem.name === 'ІТМ').uid,
    uid: uuid(),
  }, {
    name: 'Прикладна математика',
    faculty_uid: faculties.find(elem => elem.name === 'ІТМ').uid,
    uid: uuid(),
  }, {
    name: 'Мікро- та наносистемна техніка',
    faculty_uid: faculties.find(elem => elem.name === 'ЕЛБІ').uid,
    uid: uuid(),
  }, {
    name: 'Метрологія та інформаційно-вимірювальна техніка',
    faculty_uid: faculties.find(elem => elem.name === 'ІК').uid,
    uid: uuid(),
  }, {
    name: 'Метрологія та інформаційно-вимірювальна техніка',
    faculty_uid: faculties.find(elem => elem.name === 'ЕЛБІ').uid,
    uid: uuid(),
  }, {
    name: 'Кібербезпека',
    faculty_uid: faculties.find(elem => elem.name === 'КІУ').uid,
    uid: uuid(),
  }, {
    name: 'Кібербезпека',
    faculty_uid: faculties.find(elem => elem.name === 'ІК').uid,
    uid: uuid(),
  }, {
    name: 'Кібербезпека',
    faculty_uid: faculties.find(elem => elem.name === 'ІРТЗІ').uid,
    uid: uuid(),
  }, {
    name: 'Комп`ютерні науки',
    faculty_uid: faculties.find(elem => elem.name === 'КН').uid,
    uid: uuid(),
  }, {
    name: 'Комп`ютерні науки',
    faculty_uid: faculties.find(elem => elem.name === 'ІРТЗІ').uid,
    uid: uuid(),
  }, {
    name: 'Комп`ютерні науки',
    faculty_uid: faculties.find(elem => elem.name === 'ІТМ').uid,
    uid: uuid(),
  }, {
    name: 'Комп`ютерна інженерія',
    faculty_uid: faculties.find(elem => elem.name === 'КІУ').uid,
    uid: uuid(),
  }, {
    name: 'Електроніка',
    faculty_uid: faculties.find(elem => elem.name === 'ІРТЗІ').uid,
    uid: uuid(),
  }, {
    name: 'Електроніка',
    faculty_uid: faculties.find(elem => elem.name === 'ЕЛБІ').uid,
    uid: uuid(),
  }, {
    name: 'Електроніка',
    faculty_uid: faculties.find(elem => elem.name === 'ІТМ').uid,
    uid: uuid(),
  }, {
    name: 'Видавництво та поліграфія',
    faculty_uid: faculties.find(elem => elem.name === 'КН').uid,
    uid: uuid(),
  }, {
    name: 'Біомедична інженерія',
    faculty_uid: faculties.find(elem => elem.name === 'ЕЛБІ').uid,
    uid: uuid(),
  }, {
    name: 'Авіоніка',
    faculty_uid: faculties.find(elem => elem.name === 'АКТ').uid,
    uid: uuid(),
  }, {
    name: 'Автоматизація та комп’ютерно-інтегровані технології',
    faculty_uid: faculties.find(elem => elem.name === 'АКТ').uid,
    uid: uuid(),
  }, {
    name: 'Економіка',
    faculty_uid: faculties.find(elem => elem.name === 'ІТМ').uid,
    uid: uuid(),
  },
];
const specializations = [
  // TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY
  {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Інженерія програмного забезпечення',
    name: 'Інженерія програмного забезпечення',
    volume: 25,
    period: '1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Системи штучного інтелекту',
    volume: 2,
    period: '1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '125',
    field_of_knowledge: 'Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Безпека інформаційних і комунікаційних систем',
    volume: 5,
    period: '1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Безпека державних Інформаційних ресурсів',
    volume: 5,
    period: '1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '163',
    field_of_knowledge: '16. Хімічна та біоінженерія',
    faculty: 'ЕЛБІ',
    specialty: 'Біомедична інженерія',
    name: 'Біомедична інженерія',
    volume: 10,
    period: '1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Телекомунікаційні системи та мережі',
    volume: 1,
    period: ' 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.SECOND_EDUCATION_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інформаційні мережі зв`язку',
    volume: 10,
    period: ' 1 р. 10 м.',
    cost: '11900 грн.',
  },

  // TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL
  {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '051',
    field_of_knowledge: '05. Соціальні та поведінкові науки',
    specialty: 'Економіка',
    name: 'Економічна кібернетика',
    faculty: 'ІТМ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '073',
    field_of_knowledge: '07. Управління та адміністрування',
    specialty: 'Менеджмент',
    name: 'Управління фінансово-економічною безпекою',
    faculty: 'ІТМ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІРТЗІ',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційно-комунікаційні технології',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційні управляючі системи та технології',
    volume: 15,
    period: '1 р. 5 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Системи штучного інтелекту',
    volume: 30,
    period: '1 р. 5 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '123',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Комп`ютерна інженерія',
    name: 'Комп’ютерні системи та мережі',
    volume: 25,
    period: '1 р. 5 м. - 1 р. 10 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '123',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Комп`ютерна інженерія',
    name: 'Системне програмування',
    volume: 20,
    period: '1 p. 5 м. ; 1 р. 10 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІРТЗІ',
    specialty: 'Кібербезпека',
    name: 'Системи технічного захисту інформації',
    volume: 13,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Безпека інформаційних і комунікаційних систем',
    volume: 7,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІК',
    specialty: 'Кібербезпека',
    name: 'Адміністративний менеджмент у сфері захисту информації',
    volume: 5,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '151',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'АКТ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Комп’ютерно-інтегровані технологічні процеси і виробництва',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '151',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'АКТ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Автоматизоване управління технологічними процесами',
    volume: 15,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ЕЛБІ',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Лазерна і оптоелектронна техніка ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '163',
    field_of_knowledge: '16. Хімічна та біоінженерія',
    faculty: 'ЕЛБІ',
    specialty: 'Біомедична інженерія',
    name: 'Біомедична інженерія',
    volume: 20,
    period: '1 p. 5 м. ; 1 р. 10 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '163',
    field_of_knowledge: '16. Хімічна та біоінженерія',
    faculty: 'ЕЛБІ',
    specialty: 'Біомедична інженерія',
    name: 'Ортопедичні технології та інженерії ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '171',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ЕЛБІ',
    specialty: 'Електроніка',
    name: 'Електронні прилади та пристрої ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інфокомунікаційна інженерія',
    volume: 8,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіотехніка',
    volume: 43,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Апаратура радіозв’язку, радіомовлення і телебачення ',
    volume: 35,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'АКТ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіоелектронні апарати та засоби ',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'АКТ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інтелектуальні технології мікросистемної радіоелектронної техніки',
    volume: 35,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інфокомунікаційні мережі зв`язку',
    volume: 15,
    period: '1 р. 5 м. , 1 р. 10 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Телекомунікаційні системи та мережі',
    volume: 10,
    period: '1 р. 5 м. , 1 р. 10 м.',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інфокомунікаційна інженерія',
    volume: 10,
    period: '1 р. 5 м. ',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інформаційно-мережна інженерія',
    volume: 11,
    period: '1 р. 5 м. ',
    cost: '7500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_EXTRAMURAL,
    cipher: '186',
    field_of_knowledge: '18. Виробництво та технології',
    faculty: 'КН',
    specialty: 'Видавництво та поліграфія',
    name: 'Технології друкованих видань',
    volume: 12,
    period: '1 р. 5 м.',
    cost: '7500 грн.',
  },

  // TYPES_OF_SPECIALIZATIONS.MASTER_DAILY
  {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '051',
    field_of_knowledge: '05. Соціальні та поведінкові науки',
    specialty: 'Економіка',
    name: 'Економічна кібернетика',
    faculty: 'ІТМ',
    volume: 60,
    period: '1 р. 5 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '073',
    field_of_knowledge: '07. Управління та адміністрування',
    specialty: 'Менеджмент',
    name: 'Управління фінансово-економічною безпекою',
    faculty: 'ІТМ',
    volume: 30,
    period: '1 р. 5 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '113',
    field_of_knowledge: '11. Математика та статистика',
    faculty: 'ІТМ',
    specialty: 'Прикладна математика',
    name: 'Прикладна математика',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '12900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '113',
    field_of_knowledge: '11. Математика та статистика',
    faculty: 'ІТМ',
    specialty: 'Прикладна математика',
    name: 'Криптологія',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '12900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Інженерія програмного забезпечення',
    name: 'Програмне забезпечення систем  ',
    volume: 70,
    period: '1 р. 5 м.',
    cost: '14900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Інженерія програмного забезпечення',
    name: 'Інженерія програмного забезпечення',
    volume: 50,
    period: '1 р. 5 м.',
    cost: '14900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Інформатика',
    volume: 54,
    period: '1 р. 5 м.',
    cost: '14900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Соціальна інформатика',
    volume: 15,
    period: '1 р. 5 м.',
    cost: '12900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційно-комунікаційні технології',
    volume: 30,
    period: '1 р. 10 м.',
    cost: '12900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційні управляючі системи та технології',
    volume: 24,
    period: '1 р. 5 м.',
    cost: '14900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційні технології проектування',
    volume: 29,
    period: '1 р. 5 м.',
    cost: '14900 грн',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '121',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Data Science ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '34000 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІТМ',
    specialty: 'Комп`ютерні науки',
    name: ' Консолідована інформація',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Системне проектування',
    volume: 28,
    period: '1 р. 5 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Системи штучного інтелекту ',
    volume: 52,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІТМ',
    specialty: 'Комп`ютерні науки',
    name: 'Консолідована інформація',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '122',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КН',
    specialty: 'Комп`ютерні науки',
    name: 'Управління проектами в галузі інформаційних технологій ',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '123',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Комп`ютерна інженерія',
    name: 'Комп’ютерні системи та мережі',
    volume: 55,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '123',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Комп`ютерна інженерія',
    name: 'Системне програмування ',
    volume: 54,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '123',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Комп`ютерна інженерія',
    name: 'Спеціалізовані комп’ютерні системи',
    volume: 60,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '14900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '124',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІТМ',
    specialty: 'Системний аналіз',
    name: 'Системний аналіз і управління',
    volume: 25,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '124',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІТМ',
    specialty: 'Системний аналіз',
    name: 'Консолідована інформація ',
    volume: 30,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Безпека інформаційних і комунікаційних систем',
    volume: 52,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Безпека державних інформаційних ресурсів',
    volume: 23,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'КІУ',
    specialty: 'Кібербезпека',
    name: 'Адміністративний менеджмент у сфері захисту інформації',
    volume: 40,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '125',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'ІРТЗІ',
    specialty: 'Кібербезпека',
    name: 'Системи технічного захисту інформації, авторизація її обробки',
    volume: 62,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '151',
    field_of_knowledge: '12. Інформаційні технології',
    faculty: 'АКТ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Комп’ютеризовані системи управління та автоматика',
    volume: 50,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '151',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'КІУ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Комп’ютеризовані та робототехнічні системи',
    volume: 45,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '151',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'АКТ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Автоматизоване управління технологічними процесами',
    volume: 55,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '151',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'АКТ',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Комп’ютерно-інтегровані технологічні процеси і виробництва',
    volume: 55,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ІК',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Метрологія та вимірювальна техніка',
    volume: 20,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ІК',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Метрологічне забезпечення випробувань та якості продукції ',
    volume: 20,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ІК',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Якість, стандартизація та сертифікація',
    volume: 15,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ЕЛБІ',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Фотоніка та оптоінформатика ',
    volume: 30,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '153',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ЕЛБІ',
    specialty: 'Мікро- та наносистемна техніка',
    name: 'Мікро- та наноелектроннні прилади і пристрої ',
    volume: 36,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '152',
    field_of_knowledge: '15. Автоматизація та приладобудування',
    faculty: 'ЕЛБІ',
    specialty: 'Мікро- та наносистемна техніка',
    name: 'Лазерна і оптоелектронна техніка ',
    volume: 10,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '163',
    field_of_knowledge: '16. Хімічна та біоінженерія',
    faculty: 'ЕЛБІ',
    specialty: 'Біомедична інженерія',
    name: 'Біомедична інженерія ',
    volume: 70,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '163',
    field_of_knowledge: '16. Хімічна та біоінженерія',
    faculty: 'ЕЛБІ',
    specialty: 'Біомедична інженерія',
    name: 'Інформаційні технології в біомедицині ',
    volume: 20,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '171',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Електроніка',
    name: 'Системи, технології і комп\'ютерні засоби мультимедіа',
    volume: 36,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '171',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ЕЛБІ',
    specialty: 'Електроніка',
    name: 'Електронні прилади та пристрої',
    volume: 60,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інфокомунікаційна інженерія',
    volume: 22,
    period: '1 р. 5 м. ; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіотехніка',
    volume: 41,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інженерія відновлюваних джерел енергії',
    volume: 23,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Апаратура радіозв’язку, радіомовлення і телебачення',
    volume: 45,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'АКТ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіоелектронні апарати та засоби',
    volume: 62,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІРТЗІ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіоелектронні пристрої,системи та комплекси',
    volume: 23,
    period: '1 р. 5 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Телекомунікаційні системи та мережі',
    volume: 80,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'АКТ',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інтелектуальні технології мікросистемної радіоелектронної техніки',
    volume: 91,
    period: '1 р. 5 м.; ',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інформаційні мережі зв`язку',
    volume: 28,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '172',
    field_of_knowledge: '17. Електроніка та телекомунікації',
    faculty: 'ІК',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інформаційно-мережна інженерія',
    volume: 29,
    period: '1 р. 5 м.; 1 р. 10 м.',
    cost: '11900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '186',
    field_of_knowledge: '18. Видавництво та технології',
    faculty: 'КН',
    specialty: 'Видавництво та поліграфія',
    name: 'Технологія друкованих видань (КН)',
    volume: 8,
    period: '1 р. 5 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '186',
    field_of_knowledge: '18. Видавництво та технології',
    faculty: 'КН',
    specialty: 'Видавництво та поліграфія',
    name: 'технології електронних мультімедійних видань (КН)',
    volume: 18,
    period: '1 р. 5 м. ; 1 р. 10 м.',
    cost: '12900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.MASTER_DAILY,
    cipher: '186',
    field_of_knowledge: '18. Видавництво та технології',
    faculty: 'КН',
    specialty: 'Видавництво та поліграфія',
    name: 'Комп’ютерні технології та системи Видавничо-поліграфічих Виробництв (кн)',
    volume: 15,
    period: '1 р. 5 м. ; 1 р. 10 м.',
    cost: '12900 грн.',
  },

  // TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL
  {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '051',
    specialty: 'Економіка',
    faculty: 'ІТМ',
    name: 'Економічна кібернетика',
    volume: 130,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '121',
    specialty: 'Інженерія програмного забезпечення',
    faculty: 'КН',
    name: 'Програмна інженерія',
    volume: 100,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    faculty: 'КН',
    name: 'Комп’ютерні науки',
    volume: 88,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    faculty: 'КН',
    name: 'Штучний інтелект',
    volume: 25,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '123',
    specialty: 'Комп`ютерна інженерія',
    faculty: 'КІУ',
    name: 'Комп’ютерна інженерія',
    volume: 115,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '125',
    specialty: 'Кібербезпека',
    faculty: 'КІУ',
    name: 'Безпека інформаційних і комунікаційних систем',
    volume: 40,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '125',
    specialty: 'Кібербезпека',
    faculty: 'ІРТЗІ',
    name: 'Системи технічного захисту інформації',
    volume: 22,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '151',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    faculty: 'АКТ',
    name: 'Автоматизація та комп’ютерно-інтегровані технології',
    volume: 35,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '151',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    faculty: 'АКТ',
    name: 'Системна інженерія',
    volume: 20,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '152',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    faculty: 'ЕЛБІ',
    name: 'Оптотехніка',
    volume: 70,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '163',
    specialty: 'Біомедична інженерія',
    faculty: 'ЕЛБІ',
    name: 'Біомедична інженерія',
    volume: 18,
    period: '4 р. 10 м.',
    cost: '4600 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    faculty: 'ІРТЗІ',
    name: 'Радіотехніка',
    volume: 20,
    period: '4 р. 10 м.',
    cost: '4600 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    faculty: 'АКТ',
    name: 'Інтелектуальні технології засобів радіоелектроніки',
    volume: 75,
    period: '4 р. 10 м.',
    cost: '4600 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    faculty: 'АКТ',
    name: 'Радіоелектронні засоби вбудованих систем',
    volume: 20,
    period: '4 р. 10 м.',
    cost: '4600 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    faculty: 'ІК',
    name: 'Інфокомунікаційна інженерія',
    volume: 89,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    faculty: 'ІК',
    name: 'Інформаційно-мережна інженерія',
    volume: 83,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '173',
    specialty: 'Авіоніка',
    faculty: 'АКТ',
    name: 'Вбудовані системи авіоніки',
    volume: 30,
    period: '4 р. 10 м.',
    cost: '4600 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_EXTRAMURAL,
    cipher: '186',
    specialty: 'Видавництво та поліграфія',
    faculty: 'КН',
    name: 'Видавничо-поліграфічна справа',
    volume: 45,
    period: '4 р. 10 м.',
    cost: '5500 грн.',
  },

  // TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY
  {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '051',
    specialty: 'Економіка',
    name: 'Економічна кібернетика',
    faculty: 'ІТМ',
    marks: 'У - 0.3; М - 0.3; ІМ/Ф - 0.3; А - 0.1;',
    minMark: 164.75,
    volume: 250,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '113',
    specialty: 'Прикладна математика',
    name: 'Прикладна математика',
    faculty: 'ІТМ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 152.65,
    volume: 75,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '113',
    specialty: 'Прикладна математика',
    name: 'Криптологія',
    faculty: 'ІТМ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 25,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '121',
    specialty: 'Інженерія програмного забезпечення',
    name: 'Програмна інженерія',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 176.9,
    volume: 355,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    name: 'Інформатика',
    faculty: 'ІТМ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 166.05,
    volume: 200,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    name: 'Консолідована інформація',
    faculty: 'ІТМ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 20,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    name: 'Інформаційно-комунікаційні технології',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 40,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    name: 'Комп’ютерні науки',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 166.1,
    volume: 412,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '122',
    specialty: 'Комп`ютерні науки',
    name: 'Штучний інтелект',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 60,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '123',
    specialty: 'Комп`ютерна інженерія',
    name: 'Комп’ютерна інженерія',
    faculty: 'КІУ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 157.65,
    volume: 475,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '124',
    specialty: 'Системний аналіз',
    name: 'Системний аналіз',
    faculty: 'ІТМ',
    marks: 'У - 0.2; М - 0.45; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 151.95,
    volume: 100,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '125',
    specialty: 'Кібербезпека',
    name: 'Безпека інформаційних і комунікаційних систем',
    faculty: 'КІУ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 155.1,
    volume: 160,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '125',
    specialty: 'Кібербезпека',
    name: 'Системи технічного захисту інформації',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 155.35,
    volume: 98,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '125',
    specialty: 'Кібербезпека',
    name: 'Управління інформаційною безпекою',
    faculty: 'ІК',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 155.2,
    volume: 50,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '126',
    specialty: 'Інформаційні системи та технології',
    name: 'Інформаційні системи та технології',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 35,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '126',
    specialty: 'Інформаційні системи та технології',
    name: 'Інформаційні технологіїї інтернету речей',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 50,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '126',
    specialty: 'Інформаційні системи та технології',
    name: 'Інформаційні системи в медицині',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.5; ІМ/Ф - 0.2; А - 0.1;',
    minMark: 164.75,
    volume: 15,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '151',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Автоматизація та комп’ютерно-інтегровані технології',
    faculty: 'АКТ',
    marks: 'У - 0.25; М - 0.4; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 141,
    volume: 85,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '151',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Автоматизація та комп’ютерно-інтегровані ресурсозберігаючі техноогії. Альтернативна енергетика',
    faculty: 'АКТ',
    marks: 'У - 0.25; М - 0.4; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 60,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '151',
    specialty: 'Автоматизація та комп’ютерно-інтегровані технології',
    name: 'Системна інженерія',
    faculty: 'АКТ',
    marks: 'У - 0.25; М - 0.4; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 140.6,
    volume: 140,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '152',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Оптотехніка',
    faculty: 'ЕЛБІ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 133.65,
    volume: 70,
    period: '3 р. 10 м.',
    cost: '10900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '152',
    specialty: 'Метрологія та інформаційно-вимірювальна техніка',
    name: 'Технічна експертиза',
    faculty: 'ІК',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 150,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '153',
    specialty: 'Мікро- та наносистемна техніка',
    name: 'Мікро- та наноелектроніка',
    faculty: 'ЕЛБІ',
    marks: 'У - 0.2; М - 0.45; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 135.65,
    volume: 240,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '163',
    specialty: 'Біомедична інженерія',
    name: 'Біомедична інженерія',
    faculty: 'ЕЛБІ',
    marks: 'У - 0.2; Б - 0.35; ІМ/М - 0.3; А - 0.1; П - 0.05;',
    minMark: 158.85,
    volume: 132,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '171',
    specialty: 'Електроніка',
    name: 'Системи, технології і комп\'ютерні засоби мультімедіа',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.2; П - 0.05;',
    minMark: 164.75,
    volume: 65,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '171',
    specialty: 'Електроніка',
    name: 'Електронні пристрої та системи',
    faculty: 'ЕЛБІ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 139.65,
    volume: 128,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіотехніка',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.3; М - 0.3; ІМ/Ф - 0.3; А - 0.1; П - 0.05;',
    minMark: 132.2,
    volume: 545,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інженерія відновлюваних джерел енергії',
    faculty: 'ІРТЗІ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 133,
    volume: 35,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інтелектуальні технології засобів радіоелектроніки',
    faculty: 'АКТ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 230,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Радіоелектронні засоби вбудованих систем',
    faculty: 'АКТ',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 50,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Телекомунікації',
    faculty: 'ІК',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 130.45,
    volume: 210,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інфокомунікаційна інженерія',
    faculty: 'ІК',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 60,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '172',
    specialty: 'Телекомунікації та радіотехніка',
    name: 'Інформаційно-мережна інженерія',
    faculty: 'ІК',
    marks: 'У - 0.3; М - 0.35; ІМ/Ф - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 67,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '173',
    specialty: 'Авіоніка',
    name: 'Вбудовані системи авіоніки',
    faculty: 'АКТ',
    marks: 'У - 0.3; М - 0.35; ІМ/ІУ - 0.2; А - 0.1; П - 0.05;',
    minMark: 164.75,
    volume: 100,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  }, {
    type_of_specialization: TYPES_OF_SPECIALIZATIONS.BACHELOR_DAILY,
    cipher: '186',
    specialty: 'Видавництво та поліграфія',
    name: 'Видавничо-поліграфічна справа',
    faculty: 'КН',
    marks: 'У - 0.2; М - 0.45; Ф/ІМ/Х - 0.2; А - 0.1; П - 0.05;',
    minMark: 152.25,
    volume: 205,
    period: '3 р. 10 м.',
    cost: '9900 грн.',
  },
];

const admissionComponents = [
  { id: 1, name: 'Спеціальності, за якими проводиться прийом на 1 курс до ХНУРЕ', value: 'specialities' },
  { id: 2, name: 'Приймальна комісія', value: 'selectionCommittee' },
  { id: 3, name: 'Правила прийому', value: 'admissionRules' },
  { id: 4, name: 'Порядок подання документів', value: 'documentsSubmission' },
  { id: 5, name: 'Робота зі школярами', value: 'schoolWork' },
  { id: 6, name: 'Робота з технікумами', value: 'colledgeWork' },
  { id: 7, name: 'Центр довузівської підготовки' },
  { id: 8, name: 'Заходи' },
  { id: 9, name: 'Для іноземних громадян' },
  { id: 10, name: 'Для майбутніх магістрів' },
  { id: 11, name: 'Друга вища освіта' }
];

export const announcementsMock = () => {
  return announcements
};

export const newsMock = () => {
  return news
};

export const facultiesMock = () => {
  return faculties
};

export const specialitiesMock = () => {
  return specialities
};

export const specializationsMock = () => {
  return specializations.map(specialization => {
    const findedFaculty = faculties.find(faculty => faculty.name === specialization.faculty);
    if (!findedFaculty) return; // skip crappy data

    const facultyUid = findedFaculty.uid;

    const findedSpecialty = specialities.find(specialty => {
      return specialty.name === specialization.specialty && specialty.faculty_uid === facultyUid;
    });
    if (!findedSpecialty) return; // skip crappy data

    const specialtyUid = findedSpecialty.uid;

    const specializationResult = { ...specialization };

    delete specializationResult.faculty;
    delete specializationResult.specialty;

    return {
      ...specializationResult,
      speciality_uid: specialtyUid,
    }
  }).filter(x => x);
};

export const admissionComponentsMock = () => {
  return admissionComponents
}
