import keyMirror from 'keymirror'

export const GETTERS = keyMirror({
  // USER - current user
  GET_USER_SCOPE: null,
  GET_USER_ADMIN_ACCESS: null,

  // ENTITIES - not need getters from entities now, maybe will need tomorrow

  // ANNOUNCEMENTS
  GET_ANNOUNCEMENTS: null,

  // NEWS
  GET_NEWS: null,

  // FACULTIES
  GET_FACULTIES: null,

  // SPECIALITIES
  GET_SPECIALITIES: null,

  // SPECIALIZATIONS
  GET_SPECIALIZATIONS: null,
  GET_BACHELOR_DAILY_SPECIALIZATIONS: null,
  GET_BACHELOR_EXTRAMURAL_SPECIALIZATIONS: null,
  GET_MASTER_DAILY_SPECIALIZATIONS: null,
  GET_MASTER_EXTRAMURAL_SPECIALIZATIONS: null,
  GET_SECOND_EDUCATION_DAILY_SPECIALIZATIONS: null,
  GET_SECOND_EDUCATION_EXTRAMURAL_SPECIALIZATIONS: null,

  // MODALS
  GET_OLYMPIAD_MODAL: null,
});
